# basic options
title: Efim's Blog
author: Efim Losev
email: efimius@gmail.com
github_user: efimlosev
description: >-
 Efim Losev, Sys Admin. Ideas, Thoughts, Updates


# Build settings
markdown: kramdown
theme: minima