---
title: Efim's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Efim Losev
email: efimius@gmail.com
github_username: efimlosev
description: Efim Losev, Sys Admin. Ideas, Thoughts, Updates
markdown: kramdown
theme: minima
